# Generated by Django 3.1.5 on 2021-01-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_neighborhood_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.neighbourhood'),
        ),
    ]
